#!/usr/bin/env node

/**
 * Cross-platform environment configuration helper.
 *
 * Prompts for Appwrite credentials and writes:
 *   - .env              (Vite / client / root .env with VITE_APPWRITE_* prefix)
 *   - server/.env       (server scripts with APPWRITE_* prefix, no VITE_)
 *
 * This works around the current codebase split where server scripts under
 * server/scripts/ explicitly load server/.env and expect non-prefixed keys.
 */

import fs from 'fs';
import path from 'path';
import readline from 'readline';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..', '..');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

const lineQueue = [];
let lineResolver = null;
let inputClosed = false;

rl.on('line', (line) => {
  lineQueue.push(line.trim());
  flushLine();
});

rl.on('close', () => {
  inputClosed = true;
  flushLine();
});

function flushLine() {
  if (!lineResolver) return;
  if (lineQueue.length > 0) {
    const resolve = lineResolver;
    lineResolver = null;
    resolve(lineQueue.shift());
  } else if (inputClosed) {
    const resolve = lineResolver;
    lineResolver = null;
    resolve(null);
  }
}

function ask(question, defaultValue = '') {
  return new Promise((resolve) => {
    const prompt = defaultValue ? `${question} [${defaultValue}]: ` : `${question}: `;
    process.stdout.write(prompt);
    lineResolver = (line) => {
      resolve(line || defaultValue);
    };
    rl.resume();
    flushLine();
  });
}

async function askChoice(question, choices, defaultIndex = 0) {
  console.log(`\n${question}`);
  choices.forEach((choice, index) => {
    console.log(`  ${index + 1}. ${choice}`);
  });
  const answer = await ask('Enter choice', String(defaultIndex + 1));
  const index = parseInt(answer, 10) - 1;
  if (isNaN(index) || index < 0 || index >= choices.length) {
    console.log('Invalid choice, using default.');
    return defaultIndex;
  }
  return index;
}

function loadExistingEnv(envPath) {
  if (!fs.existsSync(envPath)) return {};
  const content = fs.readFileSync(envPath, 'utf8');
  const vars = {};
  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const index = trimmed.indexOf('=');
    if (index === -1) continue;
    const key = trimmed.slice(0, index).trim();
    let value = trimmed.slice(index + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    vars[key] = value;
  }
  return vars;
}

function buildEnvContent(entries) {
  const lines = ['# Appwrite Configuration', '# Generated by scripts/setup/configure-env.js', ''];
  for (const [key, value, comment] of entries) {
    if (comment) lines.push(`# ${comment}`);
    lines.push(`${key}=${value}`);
  }
  lines.push('');
  return lines.join('\n');
}

async function main() {
  console.log('=== Village Management System Environment Setup ===\n');

  const rootEnvPath = path.join(rootDir, '.env');
  const serverEnvPath = path.join(rootDir, 'server', '.env');
  const existingRoot = loadExistingEnv(rootEnvPath);
  const existingServer = loadExistingEnv(serverEnvPath);

  // If the parent setup script already asked, honour VILLAGE_BACKEND env var
  let isSelfHosted;
  const backendEnv = (process.env.VILLAGE_BACKEND || '').toLowerCase();
  if (backendEnv === 'self-hosted') {
    console.log('\nUsing self-hosted Appwrite backend (from setup wizard).');
    isSelfHosted = true;
  } else if (backendEnv === 'cloud') {
    console.log('\nUsing Appwrite Cloud backend (from setup wizard).');
    isSelfHosted = false;
  } else {
    const backendChoices = ['Appwrite Cloud (recommended)', 'Self-hosted (Docker required)'];
    const backendIndex = await askChoice(
      'Which Appwrite backend do you want to use?',
      backendChoices,
      0,
    );
    isSelfHosted = backendIndex === 1;
  }

  const defaultEndpoint = isSelfHosted ? 'http://localhost/v1' : 'https://cloud.appwrite.io/v1';
  const endpoint = await ask(
    'Appwrite endpoint',
    existingRoot.VITE_APPWRITE_ENDPOINT || existingServer.APPWRITE_ENDPOINT || defaultEndpoint,
  );

  const projectId = await ask(
    'Appwrite Project ID',
    existingRoot.VITE_APPWRITE_PROJECT_ID || existingServer.APPWRITE_PROJECT_ID || '',
  );
  if (!projectId) {
    console.error('❌ Project ID is required.');
    process.exit(1);
  }

  const apiKey = await ask(
    'Appwrite API Key (with Database + Users scopes)',
    existingRoot.VITE_APPWRITE_API_KEY || existingServer.APPWRITE_API_KEY || '',
  );
  if (!apiKey) {
    console.error('❌ API Key is required.');
    process.exit(1);
  }

  const databaseId = await ask(
    'Database ID',
    existingRoot.VITE_APPWRITE_DATABASE_ID || existingServer.APPWRITE_DATABASE_ID || 'villageDB',
  );

  // Function and table IDs use fixed defaults — the Appwrite setup script creates these.
  const functionCheckUsers = 'checkUsersExist';
  const functionWipeData = 'wipeAllData';
  const functionSeedData = 'seedAllData';
  // Story 5.4: placeholder function ID for the storageUsageReport function,
  // consistent with the other function IDs collected above.
  const storageReportFunctionId = 'storageUsageReport';
  const tableUsers = 'users';
  const tableResidents = 'residents';
  const tableHouseholds = 'households';
  const tableRoles = 'roles';
  const tableVillageSettings = 'village_settings';
  const tableInventory = 'inventory';
  const tableVillageEvents = 'village_events';
  const tableFileMetadata = 'file_metadata';
  const bucketPersonalFiles = 'personal_files';
  // Story 5.4: shared_files bucket for module-based shared folders.
  const bucketSharedFiles = 'shared_files';

  const rootEntries = [
    ['VITE_APPWRITE_ENDPOINT', endpoint, 'Appwrite API endpoint'],
    ['VITE_APPWRITE_PROJECT_ID', projectId, 'Appwrite Project ID'],
    ['VITE_APPWRITE_API_KEY', apiKey, 'Appwrite API Key (server-side setup scripts only)'],
    [
      'VITE_APPWRITE_FUNCTION_CHECK_USERS',
      functionCheckUsers,
      'Function ID for checking if users exist',
    ],
    ['VITE_APPWRITE_FUNCTION_WIPE_DATA', functionWipeData, 'Function ID for wiping all data'],
    [
      'VITE_APPWRITE_FUNCTION_SEED_DATA',
      functionSeedData,
      'Function ID for seeding all sample data',
    ],
    [
      'VITE_APPWRITE_FUNCTION_STORAGE_REPORT',
      storageReportFunctionId,
      'Function ID for the admin storage usage report',
    ],
    ['VITE_APPWRITE_DATABASE_ID', databaseId, 'Database ID'],
    ['VITE_APPWRITE_TABLE_USERS', tableUsers, 'Table IDs'],
    ['VITE_APPWRITE_TABLE_RESIDENTS', tableResidents],
    ['VITE_APPWRITE_TABLE_HOUSEHOLDS', tableHouseholds],
    ['VITE_APPWRITE_TABLE_ROLES', tableRoles],
    ['VITE_APPWRITE_TABLE_VILLAGE_SETTINGS', tableVillageSettings],
    ['VITE_APPWRITE_TABLE_INVENTORY', tableInventory],
    ['VITE_APPWRITE_TABLE_VILLAGE_EVENTS', tableVillageEvents],
    ['VITE_APPWRITE_TABLE_FILE_METADATA', tableFileMetadata],
    ['VITE_APPWRITE_BUCKET_PERSONAL_FILES', bucketPersonalFiles, 'Storage bucket IDs'],
    ['VITE_APPWRITE_BUCKET_SHARED_FILES', bucketSharedFiles],
  ];

  const serverEntries = [
    ['APPWRITE_ENDPOINT', endpoint, 'Appwrite API endpoint'],
    ['APPWRITE_PROJECT_ID', projectId, 'Appwrite Project ID'],
    ['APPWRITE_API_KEY', apiKey, 'Appwrite API Key (server-side setup scripts)'],
    ['APPWRITE_DATABASE_ID', databaseId, 'Database ID'],
    ['APPWRITE_TABLE_USERS', tableUsers, 'Table IDs'],
    ['APPWRITE_TABLE_RESIDENTS', tableResidents],
    ['APPWRITE_TABLE_HOUSEHOLDS', tableHouseholds],
    ['APPWRITE_TABLE_ROLES', tableRoles],
    ['APPWRITE_TABLE_VILLAGE_SETTINGS', tableVillageSettings],
    ['APPWRITE_TABLE_INVENTORY', tableInventory],
    ['APPWRITE_TABLE_VILLAGE_EVENTS', tableVillageEvents],
    ['APPWRITE_TABLE_FILE_METADATA', tableFileMetadata],
    ['APPWRITE_BUCKET_PERSONAL_FILES', bucketPersonalFiles, 'Storage bucket IDs'],
    ['APPWRITE_BUCKET_SHARED_FILES', bucketSharedFiles],
  ];

  fs.writeFileSync(rootEnvPath, buildEnvContent(rootEntries), { encoding: 'utf8' });
  fs.writeFileSync(serverEnvPath, buildEnvContent(serverEntries), { encoding: 'utf8' });

  console.log(`\n✅ Created ${path.relative(rootDir, rootEnvPath)}`);
  console.log(`✅ Created ${path.relative(rootDir, serverEnvPath)}`);
  console.log('\nNext: the setup script will run npm run setup:appwrite and npm run seed:roles.');
}

main()
  .then(() => {
    rl.close();
    process.exit(0);
  })
  .catch((error) => {
    console.error('❌ configure-env failed:', error.message);
    rl.close();
    process.exit(1);
  });
